# -*- coding: utf-8 -*-
"""2-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQFVys1PUk43fBAR0aBKdPEug28JrzAq
"""

print("Hello,World!")